server:
  port: 9999
logging:
  level:
    org.springframework.web.client: DEBUG

profanity:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:36268,localhost:44147
legacy:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8080
banners:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081

